script:
- echo Running $TRAVIS_BUILD_STAGE_NAME; for i in {1..99}; do echo $i; sleep 60; done

stages:
  - stage1
  - stage2
  - stage3

jobs:
  include:
  - stage: stage1
  - stage: stage2
  - stage: stage3
    script: echo This is a custom stage script
